# 1.

In [33]:
sett = {"aman", "222", 777, 400.4}
tuplee = tuple(sett)
print(tuplee)

(400.4, 'aman', '222', 777)


# 2.

In [2]:
dict1 = {"Roll Number": "CB.EN.U4CSE20247","Last Name": "Murugesan","First Name": "Prasanna","DOB": "19-06-2002"}
print(dict1)


{'Roll Number': 'CB.EN.U4CSE20247', 'Last Name': 'Murugesan', 'First Name': 'Prasanna', 'DOB': '19-06-2002'}


# 3.

In [4]:
import numpy as np
from numpy import random
arr = random.randint(0,1,size = (2,2))
print(arr)

[[0 0]
 [0 0]]


# 4.

In [35]:
abs(-1234)

1234

In [5]:
print(random.random())

0.44166956154123793


# 5.

In [6]:
print(random.randint(20,90))

20


# 6.

In [14]:
set1 = set([11,12,13,14,15])
set2 = random.choices(list(set1), k=3)
print(set2)

[11, 14, 15]


In [23]:
import random
Set1 = set([11, 12, 13, 14, 15])
UpdatedList = random.choices(list(Set1), k = 3)
print(UpdatedList)
set2 = random.choice(list(Set1))
print(set2)

[13, 11, 14]
15


# 7.

In [25]:
import os
os.getcwd()
os.chdir(r"/content/sample_data")
os.mkdir('document1')
os.chdir('document1')
f = open('document_1.txt','w+')
f.write('The King is Dead, Long Live The King')
f.seek(0)
print(f.read())
f.close()

The King is Dead, Long Live The King


# 9.

In [30]:
string = 'The King is Dead, Long Live The King'
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
str = string.split()
print(str)

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


# 10.

In [ ]:
import numpy as np
l=[10,67,89,35]
arr=np.array(l)
print("The first and second elements are",arr[0],arr[1])  

# 11.

In [ ]:
arr=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(arr)

# 12.

In [38]:
print("Second Row",arr[1:][:])
print("Second Col",arr[1:,1])
print("Length of the array :",len(arr))

Second Row [[0 0]]
Second Col [0]
Length of the array : 2


# 13.

In [8]:
list3=[]
for i in range(10):
  list3.append(np.random.randint(0,100))
oned=np.array(list3)
print("1D array :",oned)
twod=oned.reshape(5,2)
print("2D array :\n",twod)
print("Transpose :\n",twod.T)

1D array : [16 81 27 71  1 16  9 81 20 30]
2D array :
 [[16 81]
 [27 71]
 [ 1 16]
 [ 9 81]
 [20 30]]
Transpose :
 [[16 27  1  9 20]
 [81 71 16 81 30]]


# 14.

In [40]:
l1=[1,2,3]
l2=[1,2,3]
l3=[1,2,3]
newarr=np.array([l1,l2,l3])
print(newarr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# 15.

In [9]:
arr=np.array([1,2,3])
for i in range(len(arr)):
  arr[i]=9
print(arr)

[9 9 9]


# 16.

In [10]:
arr=np.array([2,4,5])
sum=0
for i in arr:
  sum+=i
print(sum)

11


# 17.

In [43]:
arr=np.array([77,74,75])
prod=1
for i in arr:
  prod*=i
print(prod)

427350


# 18.

In [44]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.median(arr))
print(np.argmax(arr))
print(np.std(arr))

12.461538461538462
367.32544378698225
56
1
1
2.0
12
19.165736192147232


# 19.

In [45]:
arr=np.array([1, 1, 7, 5, 5, 5, 4])
temp=np.array(np.unique(arr))
temp.sort()
print(temp)

[1 4 5 7]


# 20.

In [46]:
x=np.array([1,2,3])
y=np.array([0,1,1])
print(np.dot(x,y))

5


# 21.

In [48]:
import numpy as np
from numpy.linalg import eig
a = np.array([[2, -12], 
              [1, -5]])
w,v=eig(a)
print(w)
print(v)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
